version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: "weekly"
    labels:
      - "npm dependencies"
    commit-message:
      prefix: "chore"
    allow:
      - dependency-name: "@tiptap/*"
      - dependency-name: "prosemirror-*"
