version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: "weekly"
    labels:
      - "npm dependencies"
    commit-message:
      prefix: "chore"
    allow:
      - dependency-name: "@tiptap/*"
      - dependency-name: "prosemirror-*"
      - dependency-name: "react"
      - dependency-name: "react-*"
      - dependency-name: "yjs"
      - dependency-name: "y-prosemirror"
    groups:
      editor-dependencies:
        patterns:
          - "@tiptap/*"
          - "prosemirror-*"
          - "react"
          - "react-*"
          - "yjs"
          - "y-prosemirror"
